server:
  error:
    include-stacktrace: on-param
  
# datasource  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root

# jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true